title: ToolSeop Blogspot Import
description: Konversi backup Blogspot menjadi Jekyll posts
baseurl: ""
url: "https://toolseop.github.io"
markdown: kramdown
theme: null
plugins: []
exclude:
  - "test"
  - "features"
  - "benchmark"
  - "script"
  - "exe"
  - "lib"
  - "docs"
  - ".github"
  - "node_modules"

